You are tasked with building an image classification system to diff b/w diff types of animals in images. U hav a dataset of labeled images. How will u build SVM model to solve multiclass classification problem. Calculate accuracy, display  confusion matrix and classification report.

In [1]:
import tensorflow_datasets as tfds
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Load the TFDS "stanford_dogs" dataset
dataset, info = tfds.load('stanford_dogs', split='train', with_info=True)


Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/12000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stanford_dogs/incomplete.2TH44F_0.2.0/stanford_dogs-train.tfrecord*...:   …

Generating test examples...:   0%|          | 0/8580 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/stanford_dogs/incomplete.2TH44F_0.2.0/stanford_dogs-test.tfrecord*...:   0…

Dataset stanford_dogs downloaded and prepared to /root/tensorflow_datasets/stanford_dogs/0.2.0. Subsequent calls will reuse this data.


In [2]:
# Define function to preprocess images
def preprocess_img(sample):
    # Resize images to a fixed size (e.g., 100x100 pixels)
    image = tf.image.resize(sample['image'], [100, 100])
    # Normalize pixel values to range [0, 1]
    image = tf.cast(image, tf.float32) / 255.0
    label = sample['label']
    return image, label

# Apply preprocessing function to dataset
dataset = dataset.map(preprocess_img)

In [3]:
# Extract images and labels
images = []
labels = []
for image, label in dataset:
    images.append(image.numpy())  # Convert to NumPy array
    labels.append(label.numpy())  # Convert to NumPy array

images = np.array(images)
labels = np.array(labels)

# Flatten images into feature vectors
X = images.reshape(images.shape[0], -1)

# Split dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

# Feature scaling
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# Train SVM model
svm_model = SVC()
svm_model.fit(X_train, y_train)

SVC()

In [5]:
# Make predictions
y_pred = svm_model.predict(X_test)

In [6]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Display classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.058333333333333334
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [1 6 0 ... 0 1 0]
 [0 1 4 ... 0 1 0]
 ...
 [1 0 0 ... 0 3 0]
 [0 0 0 ... 1 8 0]
 [0 0 0 ... 1 4 4]]
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.27      0.27      0.27        22
           2       0.20      0.16      0.18        25
           3       0.10      0.10      0.10        20
           4       0.00      0.00      0.00        18
           5       0.08      0.04      0.05        27
           6       0.04      0.10      0.05        21
           7       0.00      0.00      0.00        23
           8       0.00      0.00      0.00        16
           9       0.00      0.00      0.00        22
          10       0.06      0.06      0.06        17
          11       0.00      0.00      0.00        18
          12       0.08      0.06      0.07        18
          13       0.14      0.06      0.08        

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
